slice_name: Revenue by Product Category (top 10)
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 10__table
  viz_type: pie
  slice_id: 5
  groupby:
  - category
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: revenue
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 57
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(revenue)
    optionName: metric_9vpt99mgu5n_f9j4o19148
    sqlExpression: null
  adhoc_filters: []
  row_limit: 10
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 3
  - 4
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["category"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":57,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(revenue)","optionName":"metric_9vpt99mgu5n_f9j4o19148","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":57,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(revenue)","optionName":"metric_9vpt99mgu5n_f9j4o19148","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"10__table","viz_type":"pie","slice_id":5,"groupby":["category"],"metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":57,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(revenue)","optionName":"metric_9vpt99mgu5n_f9j4o19148","sqlExpression":null},"adhoc_filters":[],"row_limit":10,"sort_by_metric":true,"color_scheme":"supersetColors","show_labels_threshold":5,"show_legend":true,"legendType":"scroll","legendOrientation":"top","label_type":"key","number_format":"SMART_NUMBER","date_format":"smart_date","show_labels":true,"labels_outside":true,"outerRadius":70,"innerRadius":30,"extra_form_data":{},"dashboards":[3,4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 455819d4-eae7-4103-b330-dcc8a4a95c22
version: 1.0.0
dataset_uuid: 288ed332-a097-4b14-a53f-f12f150898d3
