slice_name: metrics (AVG vs MEDIAN)
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 22__table
  viz_type: table
  slice_id: 18
  query_mode: aggregate
  groupby:
  - order_purchase_timestamp
  time_grain_sqla: P1D
  temporal_columns_lookup:
    order_purchase_timestamp: true
  metrics:
  - avg_total_value
  - median_total_value
  - diff_median_avg
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_purchase_timestamp
  order_by_cols: []
  row_limit: 1000
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 5
query_context: '{"datasource":{"id":22,"type":"table"},"force":false,"queries":[{"filters":[{"col":"order_purchase_timestamp","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"order_purchase_timestamp","label":"order_purchase_timestamp","expressionType":"SQL"}],"metrics":["avg_total_value","median_total_value","diff_median_avg"],"orderby":[["avg_total_value",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"22__table","viz_type":"table","slice_id":18,"query_mode":"aggregate","groupby":["order_purchase_timestamp"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"order_purchase_timestamp":true},"metrics":["avg_total_value","median_total_value","diff_median_avg"],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"order_purchase_timestamp"}],"order_by_cols":[],"row_limit":1000,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 38778db7-2458-4fd1-8565-7088e9b05af6
version: 1.0.0
dataset_uuid: 2a14c0e3-dad0-4aee-9da4-30bd42c4eef2
