slice_name: "new_autofresh (\u0430\u0432\u0442\u043E\u0444\u0440\u0435\u0448)"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 9__table
  viz_type: echarts_timeseries_bar
  slice_id: 12
  x_axis: review_creation_date
  time_grain_sqla: PT1M
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: review_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 49
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(review_id)
    optionName: metric_4d6hncyoci5_rsdrk3qnqsl
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: Current day
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_1fy6i2ifwmr_b0vc6ujrh57
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: review_creation_date
  limit: 5
  timeseries_limit_metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: review_creation_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 54
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: TIMESTAMP WITHOUT TIME ZONE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(review_creation_date)
    optionName: metric_motjipf6ott_3mum7m4xche
    sqlExpression: null
  order_desc: false
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 5
query_context: '{"datasource":{"id":9,"type":"table"},"force":false,"queries":[{"filters":[{"col":"review_creation_date","op":"TEMPORAL_RANGE","val":"Current
  day"}],"extras":{"time_grain_sqla":"PT1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"PT1M","columnType":"BASE_AXIS","sqlExpression":"review_creation_date","label":"review_creation_date","expressionType":"SQL"}],"metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"review_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":49,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(review_id)","optionName":"metric_4d6hncyoci5_rsdrk3qnqsl","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"review_creation_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":54,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"TIMESTAMP
  WITHOUT TIME ZONE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(review_creation_date)","optionName":"metric_motjipf6ott_3mum7m4xche","sqlExpression":null},true]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":5,"series_limit_metric":{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"review_creation_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":54,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"TIMESTAMP
  WITHOUT TIME ZONE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(review_creation_date)","optionName":"metric_motjipf6ott_3mum7m4xche","sqlExpression":null},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["review_creation_date"],"columns":[],"aggregates":{"COUNT(review_id)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"9__table","viz_type":"echarts_timeseries_bar","slice_id":12,"x_axis":"review_creation_date","time_grain_sqla":"PT1M","metrics":[{"aggregate":"COUNT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"review_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":49,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT(review_id)","optionName":"metric_4d6hncyoci5_rsdrk3qnqsl","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"Current
  day","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_1fy6i2ifwmr_b0vc6ujrh57","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"review_creation_date"}],"limit":5,"timeseries_limit_metric":{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"review_creation_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":54,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"TIMESTAMP
  WITHOUT TIME ZONE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(review_creation_date)","optionName":"metric_motjipf6ott_3mum7m4xche","sqlExpression":null},"order_desc":false,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8640759c-1bed-4df3-9d07-816616875c84
version: 1.0.0
dataset_uuid: 3864fbd8-7eb3-44a9-960e-5b51f07e8bdd
