slice_name: Revenue by Product Category (treemap 7)
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  datasource: 17__table
  viz_type: treemap_v2
  slice_id: 14
  groupby:
  - category
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_revenue
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 72
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(total_revenue)
    optionName: metric_x50hs25jhsl_pef4mkg806
    sqlExpression: null
  row_limit: 10000
  adhoc_filters: []
  color_scheme: supersetColors
  show_labels: true
  show_upper_labels: true
  label_type: key_value
  number_format: SMART_NUMBER
  date_format: smart_date
  extra_form_data: {}
  dashboards:
  - 5
query_context: '{"datasource":{"id":17,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["category"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":72,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(total_revenue)","optionName":"metric_x50hs25jhsl_pef4mkg806","sqlExpression":null}],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"17__table","viz_type":"treemap_v2","slice_id":14,"groupby":["category"],"metric":{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_revenue","description":null,"expression":null,"filterable":true,"groupby":true,"id":72,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(total_revenue)","optionName":"metric_x50hs25jhsl_pef4mkg806","sqlExpression":null},"row_limit":10000,"adhoc_filters":[],"color_scheme":"supersetColors","show_labels":true,"show_upper_labels":true,"label_type":"key_value","number_format":"SMART_NUMBER","date_format":"smart_date","extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 482fead9-e28c-41af-9682-b6c41c7fe8c7
version: 1.0.0
dataset_uuid: 8dbb8ef5-576a-41c6-b799-321077d72aed
